/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import { useGLTF } from "@react-three/drei";

export default function Model({ rotation }) {
  const { nodes, materials } = useGLTF("/3d_Earth/earth.gltf");
  return (
    <group rotation={rotation} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
        scale={1.5}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("3d_Earth/earth.gltf");
